Add ability to generate report in cobertura format
friends-of-phpspec/phpspec-code-coverage pull request #49
Opened 2021-06-11 08:34 UTC by arnaspet

Added cobertura format support, also updated docs.

2021-06-11 09:09 UTC, jaylinski requested changes

2021-06-11 09:09 UTC, jaylinski commented on src/CodeCoverageExtension.php
> +                        $reports['cobertura'] = new Report\Cobertura();
Please add a `break;` statement like above.

2021-06-11 09:18 UTC, arnaspet commented on src/CodeCoverageExtension.php
> +                        $reports['cobertura'] = new Report\Cobertura();
whoops. 😅 added.

2021-06-11 13:12 UTC, jaylinski approved these changes

2021-06-11 13:36 UTC, shulard commented
Hello @arnaspet !

Thank you for the given change. I'm ok with the commit but there are some issues during PHPSpec execution. Can you take a look ? I'll merge the change when the workflow will be green.

2021-06-14 09:12 UTC, jaylinski commented
@shulard I ran all tests on my MacBook with PHP 7.4 and couldn't reproduce those errors. Can you restart the CI pipeline? Maybe it was a fluke...

2021-06-14 09:15 UTC, arnaspet commented
yeah, really strange error, can't reproduce.

2021-06-21 09:46 UTC, shulard commented
Hello !

I've just relaunched the CI pipeline and the error is still here in the final result. @drupol, since you worked on the GitHub action part, can you take a look ?

2021-06-21 10:37 UTC, drupol commented
This is an issue that I also have. I don't know what is the issue, I've already spent a couple of hours.

In the end, I disabled the MacOS tests.

2021-06-29 08:35 UTC, jaylinski commented
@shulard I verified the failed CI tests in #50. I made no changes, but the pipelines still failed. I'd say to just merge this PR anyway (I guess you can override the CI checks). 

Maybe we have to reduce the amount of jobs we are running?

2021-07-01 13:52 UTC, arnaspet commented
Some update: I updated my macOS and after messing a bit with xcode & php version by accident some of my own phpspec tests started failing. Tried running tests inside this repo , same happened.

so i found out that it might be related with phpspec tokenizer. especially this line
https://github.com/phpspec/phpspec/blob/30dc06a0f20642d9589bb644fbcfcb1692828699/src/PhpSpec/CodeAnalysis/TokenizedNamespaceResolver.php#L119

my test.php script looks like this
```
<?php
echo preg_match('/\\\\([^\\\\]+)\s*$/', ' Bunny\Channel', $matches) . "\n";
echo preg_match('/\\\\([^\\\\]+)\s*$/', ' App\Factories\RabbitMQFactory', $matches);
```

inside my dockerised ( working fine ) php i get
```
1
1
```

but inside broken one i get 
```
1
0
```

2021-07-01 13:54 UTC, drupol commented
This is very interesting !

I don't have any MacOS at home nor at work so I cannot work on this; but it could be nice to make a kind of reproducer and open an issue on phpspec/phpspec.

2021-07-01 20:50 UTC, drupol commented
@arnaspet I opened the issue on phpspec/phpspec, we'll see how it goes.

However, I asked to multiple people to run the commands you pasted and they all return `1 1`.

So, as you have something different, could you please give us some info on the PHP version your using ? Thanks!

2021-07-02 06:34 UTC, arnaspet commented
@drupol it's 
```
➜ php --version
PHP 7.4.20 (cli) (built: Jun  4 2021 03:32:07) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.0.0, Copyright (c) 2002-2020, by Derick Rethans
```

2021-07-07 17:30 UTC, drupol commented
Could you please trigger the tests once again, it should be fixed now.

2021-09-03 12:57 UTC, arnaspet commented
@shulard 👋

2021-09-28 14:20 UTC, merged

2021-09-28 14:20 UTC, shulard commented
Hello !

I haven't the ability to rerun the workflow anymore (too old) so I just merged the code. If there are still some issues on master, please open a new PR to fix them.